frequency: 30
sensor_timeout: 0.1
two_d_mode: true
transform_time_offset: 0.0
transform_timeout: 0.0
publish_tf: true
odom_frame: odom
base_link_frame: base_link
world_frame: odom

odom0: /gazebo/ground_truth
odom0_config: [true, true, false,  # x, y, z
               false, false, true,  # roll, pitch, yaw
               false, false, false, # vx, vy, vz
               false, false, false, # vroll, vpitch, vyaw
               false, false, false] # ax, ay, az
